name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 40
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test
      run: |
        python setup.py test
        if [ "x${{ matrix.python-version }}" == "x2.7" ]; then
          cd "$(mktemp -d)"
          curl -sSL 'https://bazaar.launchpad.net/~proyvind/pyliblzma/trunk/tarball' | tar xvz
          python -m pip install --prefix=~/.local '~proyvind/pyliblzma/trunk/'
          cd -
        fi
    - name: Test
      run: |
        python setup.py test
